
development:
  adapter: mysql2
  encoding: utf8
  database: hashbg_sports_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: hashbg_sports_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: hashbg_sports
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
